name: terraform_provisoning

on:
  workflow_dispatch:

jobs:
  my_job:
    name: terraform-setup
    runs-on: self-hosted
    permissions: write-all

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        client-id: 05bdd633-73fb-4a76-9554-c013f3c6d142
        tenant-id: 768c2942-6ded-4274-a906-05c932e5a3d8
        subscription-id: 2e333137-3307-4678-a744-a2d37508c632
        
    - uses: hashicorp/setup-terraform@v3

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
    
    - name: Terraform Init
      id: init
      run: terraform init -input=false
      
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      continue-on-error: true
              
        
